webvoting/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^(?P<question_id>[0-9]+)/$',views.detail,name='detail'),
	url('^(?P<question_id>[0-9]+)/results/$',views.results,name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

webvoting/webvoting/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
	url(r'^polls/',include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

webvoting/polls/models.py
import datetime 

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	def __str__(self):
		return self.question_text

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question,on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

webvoting/polls/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render

from .models import Question

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {
		'latest_question_list' : latest_question_list,
	}
	return render(request,'polls/index.html',context)

def detail(request,question_id):
	question = get_object_or_404(Question,pk=question_id)
	return render(request,'polls/detail.html',{'question':question})


def results(request,question_id):
	response = "You are looking at results of question %s."
	return HttpResponse(response %question_id)

def vote(request,question_id):
	return HttpResponse("You'are voting on question %s." %question_id)

webvoting/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input></input>
</form>

webvoting/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}